/**
 * Vency Atelier — Shared fragrance catalog data
 * Add new entries here to grow the catalog; both coleccion and decants consume this.
 */
(function (root) {
  root.VENCY_CATALOG = [
    {
      id: 'citrus-enigma',
      name: 'Citrus Enigma',
      category: 'original-blend',
      notes: ['citrus', 'limon', 'pina', 'madera-blanca', 'almizcle'],
      noteLabels: ['Citrus', 'Limón', 'Piña', 'Madera blanca', 'Almizcle'],
      ocasion: ['diario', 'verano'],
      ocasionLabels: ['Diario', 'Verano'],
      narrative: 'La promesa de algo que nunca fue completamente dulce.',
      image: '../assets/images/originals/citrus-enigma.png',
      characterColor: 'oklch(72% 0.09 135)',
      inspiration: null,
      featured: false
    },
    {
      id: 'vency-rouge',
      name: 'Vency Rouge',
      category: 'original-blend',
      notes: ['rosa', 'especias', 'cedro', 'ambar', 'musgo'],
      noteLabels: ['Rosa de Damasco', 'Especias cálidas', 'Cedro', 'Ámbar', 'Musgo'],
      ocasion: ['noche', 'formal'],
      ocasionLabels: ['Noche', 'Formal'],
      narrative: 'Un perfume que sabe exactamente lo que es.',
      image: '../assets/images/originals/vency-rouge.png',
      characterColor: 'oklch(38% 0.10 8)',
      inspiration: null,
      featured: true
    },
    {
      id: 'infusion-carmesi',
      name: 'Infusión Carmesí',
      category: 'original-blend',
      notes: ['cereza', 'hibisco', 'rosa', 'resina', 'vetiver'],
      noteLabels: ['Cereza oscura', 'Hibisco', 'Rosa', 'Resina', 'Vetiver'],
      ocasion: ['diario', 'fin-de-semana'],
      ocasionLabels: ['Diario', 'Fin de semana'],
      narrative: 'Carmesí no como color sino como estado.',
      image: '../assets/images/originals/infusion-carmesi.png',
      characterColor: 'oklch(36% 0.10 350)',
      inspiration: null,
      featured: false
    },

    /* ── ICON SERIES ───────────────────────────────────────── */
    {
      id: 'absolu-authority',
      name: 'Absolu Authority',
      category: 'icon-series',
      notes: ['pina', 'pomelo', 'especias', 'maderas'],
      noteLabels: ['Piña', 'Pomelo', 'Especias', 'Maderas'],
      ocasion: ['noche', 'formal'],
      ocasionLabels: ['Noche', 'Formal'],
      narrative: 'La versión que no pide permiso.',
      image: '../assets/images/inspirations/absolu-authority.png',
      characterColor: 'oklch(24% 0.05 50)',
      inspiration: { name: 'Aventus Absolu', brand: 'Creed', image: null },
      featured: false
    },
    {
      id: 'after-effect',
      name: 'After Effect',
      category: 'icon-series',
      notes: ['ron', 'tabaco', 'canela', 'vainilla'],
      noteLabels: ['Ron', 'Tabaco', 'Canela', 'Vainilla'],
      ocasion: ['noche', 'fin-de-semana'],
      ocasionLabels: ['Noche', 'Fin de semana'],
      narrative: 'El rastro que queda cuando alguien que valía la pena se va.',
      image: '../assets/images/inspirations/after-effect.png',
      characterColor: 'oklch(42% 0.08 45)',
      inspiration: { name: 'Side Effect', brand: 'Initio', image: null },
      featured: false
    },
    {
      id: 'apple-whisper',
      name: 'Apple Whisper',
      category: 'icon-series',
      notes: ['manzana', 'vainilla', 'cardamomo', 'maderas'],
      noteLabels: ['Manzana', 'Vainilla', 'Cardamomo', 'Maderas'],
      ocasion: ['diario', 'fin-de-semana'],
      ocasionLabels: ['Diario', 'Fin de semana'],
      narrative: 'Una mañana de domingo que no quisiste que terminara.',
      image: '../assets/images/inspirations/apple-whisper.png',
      characterColor: 'oklch(72% 0.08 55)',
      inspiration: { name: 'Layton', brand: 'Parfums de Marly', image: null },
      featured: false
    },
    {
      id: 'aurum-mirage',
      name: 'Aurum Mirage',
      category: 'icon-series',
      notes: ['pina', 'rosa', 'vainilla', 'almizcle'],
      noteLabels: ['Piña', 'Rosa', 'Vainilla', 'Almizcle'],
      ocasion: ['noche', 'fin-de-semana'],
      ocasionLabels: ['Noche', 'Fin de semana'],
      narrative: 'Lujo tropical. El tipo de oro que no pesa.',
      image: '../assets/images/inspirations/aurum-mirage.png',
      characterColor: 'oklch(68% 0.10 75)',
      inspiration: { name: 'Lamar', brand: 'Kajal', image: null },
      featured: false
    },
    {
      id: 'cherry-desire',
      name: 'Cherry Desire',
      category: 'icon-series',
      notes: ['cereza-negra', 'rosa', 'azafran', 'ambar'],
      noteLabels: ['Cereza negra', 'Rosa', 'Azafrán', 'Ámbar'],
      ocasion: ['noche', 'formal'],
      ocasionLabels: ['Noche', 'Formal'],
      narrative: 'La cereza madura que no necesita que la pidan.',
      image: '../assets/images/inspirations/cherry-desire.png',
      characterColor: 'oklch(38% 0.12 15)',
      inspiration: { name: 'Carmina', brand: 'Creed', image: null },
      featured: false
    },
    {
      id: 'citrus-melody',
      name: 'Citrus Melody',
      category: 'icon-series',
      notes: ['citricos', 'jengibre', 'almizcle', 'maderas'],
      noteLabels: ['Cítricos brillantes', 'Jengibre', 'Almizcle', 'Maderas'],
      ocasion: ['diario', 'verano'],
      ocasionLabels: ['Diario', 'Verano'],
      narrative: 'Cítrico de lujo. La nota que no para de resonar.',
      image: '../assets/images/inspirations/citrus-melody.png',
      characterColor: 'oklch(75% 0.12 85)',
      inspiration: { name: 'Symphony', brand: 'Louis Vuitton', image: null },
      featured: false
    },
    {
      id: 'citrus-nirvana',
      name: 'Citrus Nirvana',
      category: 'icon-series',
      notes: ['toronja', 'limon', 'vetiver', 'ambar-gris'],
      noteLabels: ['Toronja', 'Limón', 'Vetiver', 'Ámbar gris'],
      ocasion: ['diario', 'verano'],
      ocasionLabels: ['Diario', 'Verano'],
      narrative: 'Cítrico puro elevado a categoría de lujo.',
      image: '../assets/images/inspirations/citrus-nirvana.png',
      characterColor: 'oklch(72% 0.10 95)',
      inspiration: { name: 'Elysium', brand: 'Roja', image: null },
      featured: false
    },
    {
      id: 'crush-effect',
      name: 'Crush Effect',
      category: 'icon-series',
      notes: ['azafran', 'vainilla', 'ambar', 'jazmin'],
      noteLabels: ['Azafrán', 'Vainilla', 'Ámbar', 'Jazmín'],
      ocasion: ['noche', 'formal'],
      ocasionLabels: ['Noche', 'Formal'],
      narrative: 'Lo que pasa cuando el azafrán y la vainilla deciden ser uno.',
      image: '../assets/images/inspirations/crush-effect.png',
      characterColor: 'oklch(60% 0.10 58)',
      inspiration: { name: 'Instant Crush', brand: 'Mancera', image: null },
      featured: false
    },
    {
      id: 'dark-sinner',
      name: 'Dark Sinner',
      category: 'icon-series',
      notes: ['cuero', 'incienso', 'vetiver', 'ambar'],
      noteLabels: ['Cuero', 'Incienso', 'Vetiver', 'Ámbar'],
      ocasion: ['noche', 'formal'],
      ocasionLabels: ['Noche', 'Formal'],
      narrative: 'Oscuro, sofisticado. El tipo de pecado que nadie lamenta.',
      image: '../assets/images/inspirations/dark-sinner.png',
      characterColor: 'oklch(26% 0.04 30)',
      inspiration: { name: 'Fetish', brand: 'Roja', image: null },
      featured: false
    },
    {
      id: 'dream-trap',
      name: 'Dream Trap',
      category: 'icon-series',
      notes: ['lichi', 'rosa', 'cacao', 'pachuli'],
      noteLabels: ['Lichi', 'Rosa', 'Cacao', 'Pachulí'],
      ocasion: ['noche', 'fin-de-semana'],
      ocasionLabels: ['Noche', 'Fin de semana'],
      narrative: 'Floral y afrutado. El sueño del que no querés despertar.',
      image: '../assets/images/inspirations/dream-trap.png',
      characterColor: 'oklch(58% 0.10 330)',
      inspiration: { name: 'Attrape-Rêves', brand: 'Louis Vuitton', image: null },
      featured: false
    },
    {
      id: 'endless-horizon',
      name: 'Endless Horizon',
      category: 'icon-series',
      notes: ['jengibre', 'toronja', 'ambar-gris', 'maderas'],
      noteLabels: ['Jengibre', 'Toronja', 'Ámbar gris', 'Maderas'],
      ocasion: ['diario', 'formal'],
      ocasionLabels: ['Diario', 'Formal'],
      narrative: 'La distancia que se siente, pero no se teme.',
      image: '../assets/images/inspirations/endless-horizon.png',
      characterColor: 'oklch(62% 0.08 230)',
      inspiration: { name: "L'Immensité", brand: 'Louis Vuitton', image: null },
      featured: false
    },
    {
      id: 'exotic-contrast',
      name: 'Exotic Contrast',
      category: 'icon-series',
      notes: ['maracuya', 'oud', 'rosa', 'cuero'],
      noteLabels: ['Maracuyá', 'Oud', 'Rosa', 'Cuero'],
      ocasion: ['noche', 'fin-de-semana'],
      ocasionLabels: ['Noche', 'Fin de semana'],
      narrative: 'Fruta exótica chocando contra oud. Una tensión adictiva.',
      image: '../assets/images/inspirations/exotic-contrast.png',
      characterColor: 'oklch(48% 0.10 42)',
      inspiration: { name: 'Oud Maracujá', brand: 'Maison Crivelli', image: null },
      featured: false
    },
    {
      id: 'fireside-memory',
      name: 'Fireside Memory',
      category: 'icon-series',
      notes: ['castana', 'vainilla', 'humo', 'madera'],
      noteLabels: ['Castaña', 'Vainilla', 'Humo', 'Madera'],
      ocasion: ['noche', 'invierno'],
      ocasionLabels: ['Noche', 'Invierno'],
      narrative: 'El olor del fuego antes de que alguien lo apague.',
      image: '../assets/images/inspirations/fireside-memory.png',
      characterColor: 'oklch(32% 0.05 30)',
      inspiration: { name: 'By the Fireplace', brand: 'Maison Margiela', image: null },
      featured: false
    },
    {
      id: 'fresh-coast',
      name: 'Fresh Coast',
      category: 'icon-series',
      notes: ['limon', 'menta', 'frutas', 'almizcle'],
      noteLabels: ['Limón', 'Menta', 'Frutas', 'Almizcle'],
      ocasion: ['diario', 'verano'],
      ocasionLabels: ['Diario', 'Verano'],
      narrative: 'El mar desde lejos, limpio como el principio de algo.',
      image: '../assets/images/inspirations/fresh-coast.png',
      characterColor: 'oklch(65% 0.08 215)',
      inspiration: { name: 'Pacific Chill', brand: 'Louis Vuitton', image: null },
      featured: false
    },
    {
      id: 'fresh-signature',
      name: 'Fresh Signature',
      category: 'icon-series',
      notes: ['pomelo', 'jengibre', 'incienso', 'sandalo'],
      noteLabels: ['Pomelo', 'Jengibre', 'Incienso', 'Sándalo'],
      ocasion: ['diario', 'formal'],
      ocasionLabels: ['Diario', 'Formal'],
      narrative: 'La misma habitación, pero alguien ha entrado.',
      image: '../assets/images/inspirations/fresh-signature.png',
      characterColor: 'oklch(52% 0.05 240)',
      inspiration: { name: 'Bleu de Chanel', brand: 'Chanel', image: null },
      featured: false
    },
    {
      id: 'golden-citrine',
      name: 'Golden Citrine',
      category: 'icon-series',
      notes: ['mango', 'jengibre', 'limon', 'maderas'],
      noteLabels: ['Mango', 'Jengibre', 'Limón', 'Maderas'],
      ocasion: ['diario', 'verano'],
      ocasionLabels: ['Diario', 'Verano'],
      narrative: 'Mango tropical que explota y no pide disculpas.',
      image: '../assets/images/inspirations/golden-citrine.png',
      characterColor: 'oklch(72% 0.12 75)',
      inspiration: { name: 'God of Fire', brand: 'Stéphane Humbert Lucas 777', image: null },
      featured: false
    },
    {
      id: 'golden-heritage',
      name: 'Golden Heritage',
      category: 'icon-series',
      notes: ['miel', 'tabaco', 'lavanda', 'vainilla'],
      noteLabels: ['Miel', 'Tabaco', 'Lavanda', 'Vainilla'],
      ocasion: ['noche', 'formal'],
      ocasionLabels: ['Noche', 'Formal'],
      narrative: 'Tabaco y miel. Un lujo que se hereda, no se compra.',
      image: '../assets/images/inspirations/golden-heritage.png',
      characterColor: 'oklch(65% 0.10 68)',
      inspiration: { name: 'Naxos', brand: 'Xerjoff', image: null },
      featured: false
    },
    {
      id: 'green-profile',
      name: 'Green Profile',
      category: 'icon-series',
      notes: ['hierba-verde', 'iris', 'sandalo', 'violeta'],
      noteLabels: ['Hierba verde', 'Iris', 'Sándalo', 'Violeta'],
      ocasion: ['formal', 'diario'],
      ocasionLabels: ['Formal', 'Diario'],
      narrative: 'La campiña en el traje de alguien que no lo parece.',
      image: '../assets/images/inspirations/green-profile.png',
      characterColor: 'oklch(50% 0.10 145)',
      inspiration: { name: 'Green Irish Tweed', brand: 'Creed', image: null },
      featured: false
    },
    {
      id: 'inner-wild',
      name: 'Inner Wild',
      category: 'icon-series',
      notes: ['tabaco', 'especias', 'maderas', 'resinas'],
      noteLabels: ['Tabaco', 'Especias', 'Maderas', 'Resinas'],
      ocasion: ['noche', 'formal'],
      ocasionLabels: ['Noche', 'Formal'],
      narrative: 'Potencia pura. Lo salvaje que lleva traje.',
      image: '../assets/images/inspirations/inner-wild.png',
      characterColor: 'oklch(38% 0.06 45)',
      inspiration: { name: 'Centaurus', brand: 'Creed', image: null },
      featured: false
    },
    {
      id: 'jagger-index',
      name: 'Jagger Index',
      category: 'icon-series',
      notes: ['tabaco', 'manzana', 'vainilla', 'canela'],
      noteLabels: ['Tabaco', 'Manzana', 'Vainilla', 'Canela'],
      ocasion: ['noche', 'fin-de-semana'],
      ocasionLabels: ['Noche', 'Fin de semana'],
      narrative: 'El escenario vacío que todavía huele a actuación.',
      image: '../assets/images/inspirations/jagger-index.png',
      characterColor: 'oklch(28% 0.04 25)',
      inspiration: { name: 'Smoking Hot', brand: 'By Kilian', image: null },
      featured: false
    },
    {
      id: 'last-light',
      name: 'Last Light',
      category: 'icon-series',
      notes: ['vainilla', 'benjui', 'ambar', 'haba-tonka'],
      noteLabels: ['Vainilla', 'Benjuí', 'Ámbar', 'Haba tonka'],
      ocasion: ['noche', 'formal'],
      ocasionLabels: ['Noche', 'Formal'],
      narrative: 'La última hora de luz antes de que el día decida terminar.',
      image: '../assets/images/inspirations/last-light.png',
      characterColor: 'oklch(58% 0.09 62)',
      inspiration: { name: 'Grand Soir', brand: 'Maison Francis Kurkdjian', image: null },
      featured: false
    },
    {
      id: 'luminous-dream',
      name: 'Luminous Dream',
      category: 'icon-series',
      notes: ['te-negro', 'citricos', 'jengibre', 'ambrox'],
      noteLabels: ['Té negro', 'Cítricos', 'Jengibre', 'Ambrox'],
      ocasion: ['diario', 'formal'],
      ocasionLabels: ['Diario', 'Formal'],
      narrative: 'Limpio, brillante y adictivo. La luminosidad como estado permanente.',
      image: '../assets/images/inspirations/luminous-dream.png',
      characterColor: 'oklch(72% 0.06 210)',
      inspiration: { name: 'Imagination', brand: 'Louis Vuitton', image: null },
      featured: false
    },
    {
      id: 'midnight-coffee',
      name: 'Midnight Coffee',
      category: 'icon-series',
      notes: ['cafe', 'vainilla', 'rosa', 'sandalo'],
      noteLabels: ['Café', 'Vainilla', 'Rosa', 'Sándalo'],
      ocasion: ['noche', 'fin-de-semana'],
      ocasionLabels: ['Noche', 'Fin de semana'],
      narrative: 'Café cremoso. La seducción que no necesita horario.',
      image: '../assets/images/inspirations/midnight-coffee.png',
      characterColor: 'oklch(28% 0.04 35)',
      inspiration: { name: 'Amore Café', brand: 'Mancera', image: null },
      featured: false
    },
    {
      id: 'neutral-state',
      name: 'Neutral State',
      category: 'icon-series',
      notes: ['lavanda', 'vetiver', 'sandalo', 'almizcle'],
      noteLabels: ['Lavanda', 'Vetiver', 'Sándalo', 'Almizcle'],
      ocasion: ['diario', 'formal'],
      ocasionLabels: ['Diario', 'Formal'],
      narrative: 'Lo que queda en el aire después de que alguien notable se ha ido.',
      image: '../assets/images/inspirations/neutral-state.png',
      characterColor: 'oklch(80% 0.004 80)',
      inspiration: { name: 'Rehab', brand: 'Initio', image: null },
      featured: false
    },
    {
      id: 'night-light',
      name: 'Night Light',
      category: 'icon-series',
      notes: ['ron', 'tabaco', 'vainilla', 'cuero'],
      noteLabels: ['Ron', 'Tabaco', 'Vainilla', 'Cuero'],
      ocasion: ['noche', 'fin-de-semana'],
      ocasionLabels: ['Noche', 'Fin de semana'],
      narrative: 'El bar a la medianoche cuando la música es lo único real.',
      image: '../assets/images/inspirations/night-light.png',
      characterColor: 'oklch(30% 0.04 40)',
      inspiration: { name: 'Replica: Jazz Club', brand: 'Maison Margiela', image: null },
      featured: false
    },
    {
      id: 'nomad-ritual',
      name: 'Nomad Ritual',
      category: 'icon-series',
      notes: ['oud', 'rosa', 'incienso', 'frambuesa'],
      noteLabels: ['Oud', 'Rosa', 'Incienso', 'Frambuesa'],
      ocasion: ['noche', 'formal'],
      ocasionLabels: ['Noche', 'Formal'],
      narrative: 'El ritual del viajero que lleva su tierra consigo.',
      image: '../assets/images/inspirations/nomad-ritual.png',
      characterColor: 'oklch(26% 0.05 35)',
      inspiration: { name: 'Ombre Nomade', brand: 'Louis Vuitton', image: null },
      featured: false
    },
    {
      id: 'phantom-ratio',
      name: 'Phantom Ratio',
      category: 'icon-series',
      notes: ['ron', 'cafe', 'chocolate-negro', 'caramelo'],
      noteLabels: ['Ron', 'Café', 'Chocolate negro', 'Caramelo'],
      ocasion: ['noche', 'fin-de-semana'],
      ocasionLabels: ['Noche', 'Fin de semana'],
      narrative: 'Gourmand oscuro. La proporción exacta entre placer y peligro.',
      image: '../assets/images/inspirations/phantom-ratio.png',
      characterColor: 'oklch(22% 0.03 15)',
      inspiration: { name: 'Black Phantom', brand: 'By Kilian', image: null },
      featured: false
    },
    {
      id: 'prime-authority',
      name: 'Prime Authority',
      category: 'icon-series',
      notes: ['pina', 'bergamota', 'abedul', 'almizcle'],
      noteLabels: ['Piña', 'Bergamota', 'Abedul ahumado', 'Almizcle'],
      ocasion: ['formal', 'diario'],
      ocasionLabels: ['Formal', 'Diario'],
      narrative: 'La primera impresión que no necesita segunda.',
      image: '../assets/images/inspirations/prime-authority.png',
      characterColor: 'oklch(35% 0.06 48)',
      inspiration: { name: 'Aventus', brand: 'Creed', image: null },
      featured: false
    },
    {
      id: 'private-reserve',
      name: 'Private Reserve',
      category: 'icon-series',
      notes: ['ruibarbo', 'cardamomo', 'iris', 'cedro'],
      noteLabels: ['Ruibarbo', 'Cardamomo', 'Iris', 'Cedro'],
      ocasion: ['formal', 'diario'],
      ocasionLabels: ['Formal', 'Diario'],
      narrative: 'Especiado y elegante. La reserva que no está en el menú.',
      image: '../assets/images/inspirations/private-reserve.png',
      characterColor: 'oklch(38% 0.08 155)',
      inspiration: { name: 'X for Men', brand: 'Clive Christian', image: null },
      featured: false
    },
    {
      id: 'queen-essence',
      name: 'Queen Essence',
      category: 'icon-series',
      notes: ['osmanthus', 'vainilla', 'azafran', 'almizcle'],
      noteLabels: ['Osmanthus', 'Vainilla', 'Azafrán', 'Almizcle'],
      ocasion: ['noche', 'formal'],
      ocasionLabels: ['Noche', 'Formal'],
      narrative: 'La seda que se siente antes de verse.',
      image: '../assets/images/inspirations/queen-essence.png',
      characterColor: 'oklch(65% 0.06 75)',
      inspiration: { name: 'Queen of Silk', brand: 'Creed', image: null },
      featured: false
    },
    {
      id: 'rose-desire',
      name: 'Rose Desire',
      category: 'icon-series',
      notes: ['lichi', 'rosa-turca', 'peonia', 'vainilla'],
      noteLabels: ['Lichi', 'Rosa turca', 'Peonía', 'Vainilla'],
      ocasion: ['noche', 'fin-de-semana'],
      ocasionLabels: ['Noche', 'Fin de semana'],
      narrative: 'La rosa que convierte la habitación en su propio perfume.',
      image: '../assets/images/inspirations/rose-desire.png',
      characterColor: 'oklch(68% 0.10 355)',
      inspiration: { name: 'Delina', brand: 'Parfums de Marly', image: null },
      featured: false
    },
    {
      id: 'rouge-elixir',
      name: 'Rouge Elixir',
      category: 'icon-series',
      notes: ['azafran', 'jazmin', 'ambar-gris', 'cedro'],
      noteLabels: ['Azafrán', 'Jazmín', 'Ámbar gris', 'Cedro'],
      ocasion: ['noche', 'formal'],
      ocasionLabels: ['Noche', 'Formal'],
      narrative: 'Dulce, mineral y etéreo. El elixir que todo el mundo reconoce.',
      image: '../assets/images/inspirations/rouge-elixir.png',
      characterColor: 'oklch(52% 0.10 22)',
      inspiration: { name: 'Baccarat Rouge 540', brand: 'Maison Francis Kurkdjian', image: null },
      featured: false
    },
    {
      id: 'sacred-oud',
      name: 'Sacred Oud',
      category: 'icon-series',
      notes: ['oud', 'azafran', 'lavanda', 'almizcle'],
      noteLabels: ['Oud', 'Azafrán', 'Lavanda', 'Almizcle'],
      ocasion: ['noche', 'formal'],
      ocasionLabels: ['Noche', 'Formal'],
      narrative: 'Oud de lujo moderno. La tradición reescrita.',
      image: '../assets/images/inspirations/sacred-oud.png',
      characterColor: 'oklch(28% 0.06 40)',
      inspiration: { name: 'Oud for Greatness', brand: 'Initio', image: null },
      featured: false
    },
    {
      id: 'santal-code',
      name: 'Santal Code',
      category: 'icon-series',
      notes: ['sandalo', 'cedro', 'cardamomo', 'cuero'],
      noteLabels: ['Sándalo', 'Cedro', 'Cardamomo', 'Cuero'],
      ocasion: ['diario', 'formal'],
      ocasionLabels: ['Diario', 'Formal'],
      narrative: 'Sándalo seco y ahumado. El código que todos reconocen.',
      image: '../assets/images/inspirations/santal-code.png',
      characterColor: 'oklch(62% 0.07 62)',
      inspiration: { name: 'Santal 33', brand: 'Le Labo', image: null },
      featured: false
    },
    {
      id: 'santal-embrace',
      name: 'Santal Embrace',
      category: 'icon-series',
      notes: ['rosa', 'sandalo', 'especias', 'almizcle'],
      noteLabels: ['Rosa', 'Sándalo', 'Especias suaves', 'Almizcle'],
      ocasion: ['diario', 'formal'],
      ocasionLabels: ['Diario', 'Formal'],
      narrative: 'El calor de algo que no tiene prisa en irse.',
      image: '../assets/images/inspirations/santal-embrace.png',
      characterColor: 'oklch(62% 0.06 58)',
      inspiration: { name: 'Santal Pao Rosa', brand: 'Guerlain', image: null },
      featured: false
    },
    {
      id: 'shadow-leather',
      name: 'Shadow Leather',
      category: 'icon-series',
      notes: ['cuero', 'cardamomo', 'palo-rosa', 'pachuli'],
      noteLabels: ['Cuero', 'Cardamomo', 'Palo rosa', 'Pachulí'],
      ocasion: ['noche', 'formal'],
      ocasionLabels: ['Noche', 'Formal'],
      narrative: 'El cuero que no pide disculpas.',
      image: '../assets/images/inspirations/shadow-leather.png',
      characterColor: 'oklch(28% 0.04 30)',
      inspiration: { name: 'Ombre Leather', brand: 'Tom Ford', image: null },
      featured: false
    },
    {
      id: 'silver-veil',
      name: 'Silver Veil',
      category: 'icon-series',
      notes: ['almendra', 'vainilla', 'heliotropo', 'sandalo'],
      noteLabels: ['Almendra amarga', 'Vainilla', 'Heliotropo', 'Sándalo'],
      ocasion: ['diario', 'formal'],
      ocasionLabels: ['Diario', 'Formal'],
      narrative: 'Cremoso y elegante. El velo que todo lo suaviza.',
      image: '../assets/images/inspirations/silver-veil.png',
      characterColor: 'oklch(78% 0.04 72)',
      inspiration: { name: 'Pegasus', brand: 'Parfums de Marly', image: null },
      featured: false
    },
    {
      id: 'smoky-mandarin',
      name: 'Smoky Mandarin',
      category: 'icon-series',
      notes: ['mandarina', 'tabaco', 'cuero', 'maderas'],
      noteLabels: ['Mandarina', 'Tabaco', 'Cuero', 'Maderas'],
      ocasion: ['noche', 'fin-de-semana'],
      ocasionLabels: ['Noche', 'Fin de semana'],
      narrative: 'Cítrico y tabaco. La combinación que no debería funcionar y no para.',
      image: '../assets/images/inspirations/smoky-mandarin.png',
      characterColor: 'oklch(55% 0.12 48)',
      inspiration: { name: 'Tobacco Mandarin', brand: 'Byredo', image: null },
      featured: false
    },
    {
      id: 'vanille-skin',
      name: 'Vanille Skin',
      category: 'icon-series',
      notes: ['vainilla', 'coco', 'almizcle-blanco', 'iris'],
      noteLabels: ['Vainilla', 'Coco', 'Almizcle blanco', 'Iris'],
      ocasion: ['diario', 'fin-de-semana'],
      ocasionLabels: ['Diario', 'Fin de semana'],
      narrative: 'Vainilla seca y sofisticada. La piel como segundo perfume.',
      image: '../assets/images/inspirations/vanille-skin.png',
      characterColor: 'oklch(78% 0.06 72)',
      inspiration: { name: 'Vanilla Powder', brand: 'Matière Première', image: null },
      featured: false
    },
  ];

  root.escHtml = function (s) {
    return String(s)
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;');
  };
})(window);
